Models
amm-poiais/medelyan pull request #1
Opened 2017-12-20 18:24 UTC by Liesando

Более-менее чистый проект, настроил модели (models.py). Проверьте, пожалуйста

П. С. Правильный ли формат у пулреквеста (название, комментарий)?

2017-12-20 19:44 UTC, Belphanior requested changes

2017-12-20 19:44 UTC, Belphanior commented on polls/models.py
> +    voter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
Голосования могут быть и анонимными

2017-12-20 20:03 UTC, Liesando commented on polls/models.py
> +    voter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
И как же мне тогда хранить результат голосования для конкретного пользователя?

2017-12-20 20:20 UTC, Liesando commented on polls/models.py
> +    voter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
Есть вариант создавать временного пользователя с айпи в качестве никнейма:)

2017-12-20 21:03 UTC, Belphanior commented on polls/models.py
> +    voter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
Что мешает сделать поле nullable? И добавить второе, куда будет писаться айпишник

2017-12-28 06:53 UTC, Belphanior approved these changes

2017-12-28 06:53 UTC, merged